# Generated by Django 5.0.5 on 2024-05-08 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254)),
                ("Otp", models.CharField(max_length=6)),
                ("Date", models.DateField(auto_now_add=True)),
                ("Time", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PhoneNumber", models.CharField(max_length=15)),
                ("Otp", models.CharField(max_length=6)),
                ("Date", models.DateField(auto_now_add=True)),
                ("Time", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "UniqueNumber",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="Unique Number"
                    ),
                ),
                ("Url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileDetail",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("PhoneNumber", models.CharField(max_length=15)),
                ("Password", models.CharField(max_length=128)),
                (
                    "Rejected",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "Accepted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("creation_time", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
